In [ ]:
1. 	
What type of join is needed when you wish to include rows that do not have matching values?
A.	Equi-join
B.	Natural join
C.	Outer join
D.	All of the above.


Answer:
C

In [ ]:
2. 	
What type of join is needed when you wish to return rows that do have matching values?
A.	Equi-join
B.	Natural join
C.	Outer join
D.	All of the above.

Answer:
D

In [ ]:
3. 	
Which of the following is true concerning a procedure?
A.	You do not create them with SQL.
B.	They do not need to have a unique name.
C.	They include procedural and SQL statements.
D.	They are the same thing as a function.


Answer:
C


What is a Stored Procedure?
A stored procedure is a prepared SQL code that you can save, so the code can be reused over and over again.
So if you have an SQL query that you write over and over again, save it as a stored procedure, and then just call it to execute it.
You can also pass parameters to a stored procedure, so that the stored procedure can act based on the parameter value(s) that is passed.

Stored Procedures are used as scripts. They run series of commands for you and you can schedule them to run at certain
times.

Functions are used as methods. You pass it something and it returns a result. Should be small and fast - does it on 
the fly.



Re procedures:
schema_name
The name of the schema to which the procedure belongs. Procedures are schema-bound. If a schema name is not specified 
when the procedure is created, the default schema of the user who is creating the procedure is automatically assigned.

procedure_name
The name of the procedure. Procedure names must comply with the rules for identifiers and must be unique within the 
schema.

Avoid the use of the sp_ prefix when naming procedures. This prefix is used by SQL Server to designate system 
procedures. Using the prefix can cause application code to break if there is a system procedure with the same name.

Local or global temporary procedures can be created by using one number sign (#) 
before procedure_name (#procedure_name) for local temporary procedures, and two number signs for global temporary procedures (##procedure_name). A local temporary procedure is visible only to the connection that created it and is dropped when that connection is closed. A global temporary procedure is available to all connections and is dropped at the end of the last session using the procedure. Temporary names cannot be specified for CLR procedures.

The complete name for a procedure or a global temporary procedure, including ##, 
cannot exceed 128 characters. The complete name for a local temporary procedure, including #, 
cannot exceed 116 characters.

In [ ]:
4. 	
A CASE SQL statement is which of the following?
A.	A way to establish an IF-THEN-ELSE in SQL.
B.	A way to establish a loop in SQL.
C.	A way to establish a data definition in SQL.
D.	All of the above.

Answer:
A

In [ ]:
5. 	
Which of the following statements is true concerning routines and triggers?
A.	Both consist of procedural code.
B.	Both have to be called to operate.
C.	Both run automatically.
D.	Both are stored in the database.

Answer:
A (looks like you have to invoke routine, because in sql it is nothing but stored procedures or functions)

explanation:
MySQL has four different types of stored SQL: triggers, events, stored procedures, and stored functions. A trigger is 
invoked automatically when an SQL statement changes rows on a specified table. An event is invoked automatically at a 
predetermined time, and can be a one-time occurrence or a regular occurrence. A stored procedure is invoked manually 
with the CALL statement, taking zero or more arguments, and can pass back values through output variables. A stored 
function is invoked manually by directly using its name, taking zero or more arguments and outputting a scalar value.


routines:
SQL routines are routines that have logic implemented with only SQL statements, including SQL Procedural Language 
(SQL PL) statements. SQL routines are characterized by having their routine-body logic contained within the CREATE 
statement that is used to create them.

Stored routines can provide improved performance because less information needs to be sent between the server and the
client. The tradeoff is that this does increase the load on the database server because more of the work is done on
the server side and less is done on the client (application) side.

In [ ]:
6. 	
Which of the following is one of the basic approaches for joining tables?
A.	Subqueries
B.	Union Join
C.	Natural join
D.	All of the above

Answer:
D

In [ ]:
7. 	
Which of the following is true concerning systems information in an RDBMS?
A.	RDBMS store database definition information in system-created tables.
B.	This information can be accessed using SQL.
C.	This information often cannot be updated by a user.
D.	All of the above.

Answer:
D

RDBMS:
RDBMS is a software system which is used to store only data which need to be stored in the form of tables. In this
kind of system, data is managed and stored in rows and columns which is known as tuples and attributes.     
    
A relational database management system (RDBMS) is a program that allows you to create, update, and administer a 
relational database. Most relational database management systems use the SQL language to access the database.

In [ ]:
8. 	
The following SQL is which type of join: SELECT CUSTOMER_T. CUSTOMER_ID, ORDER_T. CUSTOMER_ID, NAME, ORDER_ID FROM 
CUSTOMER_T,ORDER_T WHERE CUSTOMER_T. CUSTOMER_ID = ORDER_T. CUSTOMER_ID

A.	Equi-join
B.	Natural join
C.	Outer join
D.	Cartesian join

Answer:
B


An 'inner join' is not the same as an 'equi-join' in general terms.

'equi-join' means joining tables using the equality operator or equivalent. I would still call an outer join an 
'equi-join' if it only uses equality (others may disagree).

'inner join' is opposed to 'outer join' and determines how to join two sets when there is no matching value.

In [ ]:
9. 	
Embedded SQL is which of the following?
A.	Hard-coded SQL statements in a program language such as Java.
B.	The process of making an application capable of generating specific SQL code on the fly.
C.	Hard-coded SQL statements in a procedure.
D.	Hard-coded SQL statements in a trigger.

Answer:
A

Embedded SQL is a method of combining the computing power of a programming language and the database manipulation 
capabilities of SQL. Embedded SQL statements are SQL statements written inline with the program source code, of the 
host language. The embedded SQL statements are parsed by an embedded SQL preprocessor and replaced by host-language 
calls to a code library. The output from the preprocessor is then compiled by the host compiler. 
This allows programmers to embed SQL statements in programs written in any number of languages such as C/C++, 
COBOL and Fortran. This differs from SQL-derived programming languages that do not go through discrete preprocessors, 
such as PL/SQL and T-SQL.

In [ ]:
The UNION command combines the result set of two or more SELECT statements (only distinct values)

The UNION ALL command combines the result set of two or more SELECT statements (allows duplicate values).

In [ ]:
10. 	
A UNION query is which of the following?
A.	Combines the output from no more than two queries and must include the same number of columns.
B.	Combines the output from no more than two queries and does not include the same number of columns.
C.	Combines the output from multiple queries and must include the same number of columns.
D.	Combines the output from multiple queries and does not include the same number of columns.
Answer: Option C

In [ ]:
11. 	
Which of the following statements is true concerning subqueries?
A.	Involves the use of an inner and outer query.
B.	Cannot return the same result as a query that is not a subquery.
C.	Does not start with the word SELECT.
D.	All of the above.
Answer: Option A

In [ ]:
12. 	
Which of the following is a correlated subquery?
A.	Uses the result of an inner query to determine the processing of an outer query.
B.	Uses the result of an outer query to determine the processing of an inner query.
C.	Uses the result of an inner query to determine the processing of an inner query.
D.	Uses the result of an outer query to determine the processing of an outer query.
Answer: Option B

Explanation:

Correlated subquery references a column in the outer query and executes the subquery once for every row in the outer 

query while Uncorrelated subquery executes the subquery first and passes the value to the outer query.

In [ ]:
13. 	
How many tables may be included with a join?
A.	One
B.	Two
C.	Three
D.	All of the above.
Answer: Option D

In [ ]:
14. 	
The following SQL is which type of join: SELECT CUSTOMER_T. CUSTOMER_ID, ORDER_T. CUSTOMER_ID, NAME, ORDER_ID FROM CUSTOMER_T,ORDER_T ;
A.	Equi-join
B.	Natural join
C.	Outer join
D.	Cartesian join
Answer: Option D

In [ ]:
15. 	
Which of the following is true concerning triggers?
A.	You do not create them with SQL.
B.	They execute against only some applications that access a database.
C.	They have an event, condition, and action.
D.	They cannot cascade (cause another trigger to fire).
Answer: Option C

In [ ]:
The Cartesian product, also referred to as a cross-join, returns all the rows in all the tables listed in the query.  Each row in the first table is paired with all the rows in the second table.  This happens when there is no relationship defined between the two tables.  Both the AUTHOR and STORE tables have ten rows.  If we use a Cartesian join in these two tables, we will get back 100 rows.   

SQL> select
  2    author_key,
  3    store_key
  4  from
  5    author, store; 
AUTHOR_KEY  STOR
----------- ----
A101        S101
A101        S102
A101        S103
A101        S104
A101        S105
A101        S106
A101        S107
A101        S108
A101        S109
A101        S110
A102        S101
A102        S102
…
A110        S105
A110        S106
A110        S107
A110        S108
A110        S109
A110        S110 
100 rows selected.
Most of the time, we do not want a Cartesian join, and we end up with one because we failed to provide a filter on the join.  If we actually want a Cartesian join, then we should use the ANSI cross join to tell others reading the script that we actually wanted a Cartesian join.

select
  author_key,
  store_key
from
  author cross join store;
One reason to use a Cartesian join is to generate a large amount of rows to use for testing.  I can take a large table and cross join it to another large table and produce a very large results set.  If I cross join dba_objects and dba_views, I can produce the results set below.

SQL> select count(*)
  2  from
  3    dba_objects cross join dba_views; 
  COUNT(*)
----------
 164623840 
That's a lot of rows!