In [ ]:
Write a query to print the sum of all total investment values in 2016 (TIV_2016), to a scale of 2 decimal places, 
for all policy holders who meet the following criteria:

Have the same TIV_2015 value as one or more other policyholders.
Are not located in the same city as any other policyholder (i.e.: the (latitude, longitude) attribute pairs must be 
                                                            unique).
Input Format:
The insurance table is described as follows:

| Column Name | Type          |
|-------------|---------------|
| PID         | INTEGER(11)   |
| TIV_2015    | NUMERIC(15,2) |
| TIV_2016    | NUMERIC(15,2) |
| LAT         | NUMERIC(5,2)  |
| LON         | NUMERIC(5,2)  |
where PID is the policyholders policy ID, TIV_2015 is the total investment value in 2015, TIV_2016 is the total 
investment value in 2016, LAT is the latitude of the policy holder's city, and LON is the longitude of the policy holder's city.

Sample Input

| PID | TIV_2015 | TIV_2016 | LAT | LON |
|-----|----------|----------|-----|-----|
| 1   | 10       | 5        | 10  | 10  |
| 2   | 20       | 20       | 20  | 20  |
| 3   | 10       | 30       | 20  | 20  |
| 4   | 10       | 40       | 40  | 40  |

Sample Output

| TIV_2016 |
|----------|
| 45.00    |

Explanation

The first record in the table, like the last record, meets both of the two criteria.
The TIV_2015 value '10' is as the same as the third and forth record, and its location unique.

The second record does not meet any of the two criteria. Its TIV_2015 is not like any other policyholders.

And its location is the same with the third record, which makes the third record fail, too.

So, the result is the sum of TIV_2016 of the first and last record, which is 45.

In [ ]:
Using Group by and CONCAT

Select Sum(i1.TIV_2016) as TIV_2016 from
insurance i1
where i1.TIV_2015
in

(
select i2.TIV_2015 from insurance i2
group by i2.TIV_2015
having count(*)>1
) fog

and concat(i1.lat, i1.lon)

in
(
select concat(i3.lat, i3.lon) from insurance i3
group by i3.lat, i3.lon
having count(*)=1
) cat
;

Tips: Concat the LAT and LON as a whole to represent the location information.

In [ ]:
Note: These two criteria should be met without an order, so if you attempt to filter data using criteria 1 first and 
then criteria 2, you will get a wrong result.

Taking the sample input as an example, the data set will be as following after taking the first criteria.

PID	TIV_2015	TIV_2016	LAT	LON
1	10	5	10	10
3	10	30	20	20
4	10	40	40	40

Then, the second criteria cannot filter any records on this data set. So the result is 75(5+30+40), which is 
obviously wrong since the location of record with PID '3' is actually the same with the record having been filtered 
by the first criteria.

PID	TIV_2015	TIV_2016	LAT	LON
2	20	20	20	20
3	10	30	20	20